services:
  - type: web
    name: owntmrw
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SOLANA_RPC_URL
        sync: false
      - key: GITHUB_TOKEN
        sync: false
